# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_label = QtWidgets.QLabel(self.centralwidget)
        self.main_label.setEnabled(True)
        self.main_label.setGeometry(QtCore.QRect(10, 50, 641, 111))
        font = QtGui.QFont()
        font.setFamily("Onest")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.main_label.setFont(font)
        self.main_label.setObjectName("main_label")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(20, 140, 401, 81))
        font = QtGui.QFont()
        font.setFamily("Onest")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(120, 320, 556, 44))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.new_user_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Onest")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.new_user_button.setFont(font)
        self.new_user_button.setObjectName("new_user_button")
        self.horizontalLayout.addWidget(self.new_user_button)
        spacerItem = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.current_user_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Onest")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.current_user_button.setFont(font)
        self.current_user_button.setObjectName("current_user_button")
        self.horizontalLayout.addWidget(self.current_user_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.main_label.setText(_translate("MainWindow", "Welcome to our app"))
        self.label2.setText(_translate("MainWindow", "Here is what you can do:"))
        self.new_user_button.setText(_translate("MainWindow", "Ты новенький"))
        self.current_user_button.setText(_translate("MainWindow", "Ты уже смешарик"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
