"""lilbitnew

Revision ID: e3ae6b8cfcf7
Revises: fd1c4297a9ec
Create Date: 2024-04-12 01:03:31.676839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ae6b8cfcf7'
down_revision: Union[str, None] = 'fd1c4297a9ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
