# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'store.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 530)
        MainWindow.setMinimumSize(QtCore.QSize(800, 530))
        MainWindow.setMaximumSize(QtCore.QSize(800, 530))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-180, 0, 1001, 900))
        self.label.setStyleSheet("background-image: url(:/newPrefix/ui_design.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/ui_design.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, -10, 631, 111))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(48)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(193, 187, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(680, 0, 100, 100))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/sbeam.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.game_list = QtWidgets.QListWidget(self.centralwidget)
        self.game_list.setGeometry(QtCore.QRect(40, 101, 441, 391))
        font = QtGui.QFont()
        font.setFamily("Onest")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.game_list.setFont(font)
        self.game_list.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.340591, y1:0.483, x2:0.755409, y2:0.932, stop:0 rgba(36, 36, 36, 255), stop:1 rgba(97, 97, 97, 255));\n"
"selection-color: rgb(174, 160, 255);\n"
"color: rgb(193, 187, 255);\n"
"font: 87 20pt \"Onest\";\n"
"gridline-color: rgb(193, 187, 255);")
        self.game_list.setObjectName("game_list")
        self.buy_button = QtWidgets.QPushButton(self.centralwidget)
        self.buy_button.setGeometry(QtCore.QRect(520, 130, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.buy_button.setFont(font)
        self.buy_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.340591, y1:0.483, x2:0.755409, y2:0.932, stop:0 rgba(36, 36, 36, 255), stop:1 rgba(97, 97, 97, 255));\n"
"color:rgb(193, 187, 255);\n"
"selection-color: rgb(53, 53, 53);")
        self.buy_button.setObjectName("buy_button")
        self.info_button = QtWidgets.QPushButton(self.centralwidget)
        self.info_button.setGeometry(QtCore.QRect(520, 270, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.info_button.setFont(font)
        self.info_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.340591, y1:0.483, x2:0.755409, y2:0.932, stop:0 rgba(36, 36, 36, 255), stop:1 rgba(97, 97, 97, 255));\n"
"color:rgb(193, 187, 255);\n"
"selection-color: rgb(53, 53, 53);")
        self.info_button.setObjectName("info_button")
        self.users_button = QtWidgets.QPushButton(self.centralwidget)
        self.users_button.setGeometry(QtCore.QRect(520, 350, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.users_button.setFont(font)
        self.users_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.340591, y1:0.483, x2:0.755409, y2:0.932, stop:0 rgba(36, 36, 36, 255), stop:1 rgba(97, 97, 97, 255));\n"
"color:rgb(193, 187, 255);\n"
"selection-color: rgb(53, 53, 53);")
        self.users_button.setObjectName("users_button")
        self.review_button = QtWidgets.QPushButton(self.centralwidget)
        self.review_button.setGeometry(QtCore.QRect(520, 430, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.review_button.setFont(font)
        self.review_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.340591, y1:0.483, x2:0.755409, y2:0.932, stop:0 rgba(36, 36, 36, 255), stop:1 rgba(97, 97, 97, 255));\n"
"color:rgb(193, 187, 255);\n"
"selection-color: rgb(53, 53, 53);")
        self.review_button.setObjectName("review_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Sbeam Библиотека"))
        self.buy_button.setText(_translate("MainWindow", "Купить"))
        self.info_button.setText(_translate("MainWindow", "Информация"))
        self.users_button.setText(_translate("MainWindow", "Список игроков"))
        self.review_button.setText(_translate("MainWindow", "Оставить отзыв"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
