# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_User_List(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 530)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-200, -360, 1001, 900))
        self.label.setStyleSheet("background-image: url(:/newPrefix/ui_design.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/yanly/PycharmProjects/games_bd/images/ui_design.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.game_list = QtWidgets.QListWidget(Form)
        self.game_list.setGeometry(QtCore.QRect(20, 100, 561, 391))
        font = QtGui.QFont()
        font.setFamily("Onest")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.game_list.setFont(font)
        self.game_list.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.340591, y1:0.483, x2:0.755409, y2:0.932, stop:0 rgba(36, 36, 36, 255), stop:1 rgba(97, 97, 97, 255));\n"
"selection-color: rgb(174, 160, 255);\n"
"color: rgb(193, 187, 255);\n"
"font: 87 20pt \"Onest\";\n"
"gridline-color: rgb(193, 187, 255);")
        self.game_list.setObjectName("game_list")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, -10, 631, 111))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(193, 187, 255);")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Список игроков:"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
